name: delete_branch_new
on:
 pull_request:
    types: [closed]
    branches:
    - main
jobs:
  delete_branch_new:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: delete_branch_new on PR merge/close
       if: github.event.pull_request.merged == true
       run: |
         #!/bin/bash
         echo ${{ github.head_ref }}
         git branch --delete  ${{ github.head_ref }}
