name: delete_branch_new
on:
 pull_request:
    types: [closed]
    branches:
    - main
jobs:
  delete_branch_new:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        fetch-depth: 0
     - name: delete_branch_new on PR merge/close
       if: github.event.pull_request.merged == true
       run: |
         
         echo ${{ github.head_ref }}
         git checkout -b main


         echo "suresh" >> test.txt
         git branch -r
         git branch -a
         git config --global user.email "suresh@gmail.com"
         git config --global user.name "Suresh051"
         git init
         git add .
          git commit -m 'message'
         git push origin main
         #git push origin --delete remotes/origin/${{ github.head_ref }}
         git push origin –-delete remotes/origin/pr1
       env:
          GITHUB_TOKEN: ${{ github.token }}
