name: delete_branch_new
on: 
  pull_request:
    types: [Closed]
#test
jobs:
  delete_branch_new:
    runs-on: ubuntu-latest
    steps:
    - name: delete_branch_new on PR merge/close
      if: github.event.pull_request.merged == true
      run: |
         #!/bin/bash
         echo ${{ github.head_ref }}
         git branch --delete  ${{ github.head_ref }}
