name: delete_branch_new
on:
 pull_request:
    types: [closed]
    branches:
    - main
jobs:
  delete_branch_new:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        fetch-depth: 0
     - name: delete_branch_new on PR merge/close
       if: github.event.pull_request.merged == true
       run: |
         
         echo ${{ github.head_ref }}
    
         git branch -r
         git push origin --delete remotes/origin/${{ github.head_ref }}
       env:
          GITHUB_TOKEN: ${{ github.token }}
